services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.rule=Host(`adguard.home.arpa`)
      - traefik.http.routers.adguard.entrypoints=websecure
      - traefik.http.services.adguard.loadbalancer.server.port=3000

networks:
  proxy:
    external: true

